### ISSUE TITLE
CICD: add release.yml

### ISSUE THREAD

**Issue by vfedotovs** [vfedotovs/python-regex-website#18]
```yml
name: Release on main

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - name: Bump version with Commitizen
        run: cz bump --yes

      - name: Push bump commit and tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git push origin main --follow-tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
